module.exports = {
  presets: [
    ['@babel/preset-env', {
      targets: {
        node: 'current',
        browsers: [
          'last 2 versions',
          'not dead',
          'not IE 11',
        ],
      },
      useBuiltIns: 'usage',
      corejs: 3,
      modules: false,
      loose: true,
    }],
    ['@babel/preset-react', {
      runtime: 'automatic',
      development: process.env.NODE_ENV !== 'production',
    }],
    '@babel/preset-typescript',
  ],
  plugins: [
    ['@babel/plugin-transform-runtime', {
      corejs: 3,
      helpers: true,
      regenerator: true,
      useESModules: true,
    }],
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-proposal-private-methods', { loose: true }],
    ['@babel/plugin-proposal-private-property-in-object', { loose: true }],
    ['@babel/plugin-proposal-object-rest-spread', { loose: true }],
    ['@babel/plugin-proposal-nullish-coalescing-operator', { loose: true }],
    ['@babel/plugin-proposal-optional-chaining', { loose: true }],
    ['@babel/plugin-proposal-numeric-separator', { loose: true }],
    ['@babel/plugin-proposal-logical-assignment-operators', { loose: true }],
    ['@babel/plugin-proposal-partial-application', { loose: true }],
    ['@babel/plugin-proposal-pipeline-operator', { loose: true, proposal: 'minimal' }],
    ['@babel/plugin-proposal-throw-expressions', { loose: true }],
    ['@babel/plugin-proposal-function-bind', { loose: true }],
    ['@babel/plugin-proposal-export-namespace-from', { loose: true }],
    ['@babel/plugin-proposal-export-default-from', { loose: true }],
    ['@babel/plugin-proposal-do-expressions', { loose: true }],
    ['@babel/plugin-proposal-function-sent', { loose: true }],
    ['@babel/plugin-proposal-json-strings', { loose: true }],
    ['@babel/plugin-proposal-optional-catch-binding', { loose: true }],
    ['@babel/plugin-proposal-unicode-property-regex', { loose: true }],
    ['@babel/plugin-proposal-async-generator-functions', { loose: true }],
    ['@babel/plugin-proposal-dynamic-import', { loose: true }],
    ['@babel/plugin-proposal-export-namespace-from', { loose: true }],
    ['@babel/plugin-proposal-export-default-from', { loose: true }],
    ['@babel/plugin-proposal-logical-assignment-operators', { loose: true }],
    ['@babel/plugin-proposal-nullish-coalescing-operator', { loose: true }],
    ['@babel/plugin-proposal-numeric-separator', { loose: true }],
    ['@babel/plugin-proposal-object-rest-spread', { loose: true }],
    ['@babel/plugin-proposal-optional-catch-binding', { loose: true }],
    ['@babel/plugin-proposal-optional-chaining', { loose: true }],
    ['@babel/plugin-proposal-partial-application', { loose: true }],
    ['@babel/plugin-proposal-pipeline-operator', { loose: true, proposal: 'minimal' }],
    ['@babel/plugin-proposal-private-methods', { loose: true }],
    ['@babel/plugin-proposal-private-property-in-object', { loose: true }],
    ['@babel/plugin-proposal-throw-expressions', { loose: true }],
    ['@babel/plugin-proposal-unicode-property-regex', { loose: true }],
    ['@babel/plugin-syntax-dynamic-import', { loose: true }],
    ['@babel/plugin-syntax-export-default-from', { loose: true }],
    ['@babel/plugin-syntax-export-namespace-from', { loose: true }],
    ['@babel/plugin-syntax-import-meta', { loose: true }],
    ['@babel/plugin-syntax-json-strings', { loose: true }],
    ['@babel/plugin-syntax-logical-assignment-operators', { loose: true }],
    ['@babel/plugin-syntax-nullish-coalescing-operator', { loose: true }],
    ['@babel/plugin-syntax-numeric-separator', { loose: true }],
    ['@babel/plugin-syntax-object-rest-spread', { loose: true }],
    ['@babel/plugin-syntax-optional-catch-binding', { loose: true }],
    ['@babel/plugin-syntax-optional-chaining', { loose: true }],
    ['@babel/plugin-syntax-partial-application', { loose: true }],
    ['@babel/plugin-syntax-pipeline-operator', { loose: true, proposal: 'minimal' }],
    ['@babel/plugin-syntax-private-methods', { loose: true }],
    ['@babel/plugin-syntax-private-property-in-object', { loose: true }],
    ['@babel/plugin-syntax-throw-expressions', { loose: true }],
    ['@babel/plugin-syntax-top-level-await', { loose: true }],
    ['@babel/plugin-syntax-unicode-property-regex', { loose: true }],
  ],
  env: {
    development: {
      plugins: [
        // 'react-refresh/babel', // Đã được Vite tự động thêm, tránh trùng lặp
      ],
    },
    production: {
      plugins: [
        '@babel/plugin-transform-react-constant-elements',
        '@babel/plugin-transform-react-inline-elements',
        'babel-plugin-transform-react-remove-prop-types',
      ],
    },
  },
}; 